### ISSUE TITLE
How to add feature gate argument to kube-controller-manager, kube-scheduler

### ISSUE THREAD

**Issue by david-zw-liu** [linode/terraform-linode-k8s#41]
Hi, I'm new to use terraform and terraform-linode-k8s module to create k8s cluster.

I figured out that only api server append feature-gates arguments but for `kube-controller-manager`, `kube-scheduler` feature-gates arguments.

How could I add `feature-gate` simply without fork to change this project?

Thanks.

**Comment by displague** [comment]
https://github.com/linode/terraform-linode-k8s/blob/master/variables.tf#L16-L19

This affects the feature gates in the Kubelet and API server.

Beyond that, there would need to be a PR with a new variable that extends feature-gates to additional services. 

That would look similar to this: https://github.com/linode/terraform-linode-k8s/search?q=k8s_feature_gates&unscoped_q=k8s_feature_gates

Looking at the kube-controller-manager and kube-scheduler docs, it would appear that all of the Feature Flags align with the ones you can supply using the k8s_feature_gates Terraform variable.

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

```
# Keep the default flags. These are needed for the Linode CSI driver.
DEFAULT_FLAGS="CSINodeInfo=true,CSIDriverRegistry=true,BlockVolume=true,CSIBlockVolume=true"

# Add your extra flags
export TF_VAR_k8s_feature_gates="$DEFAULT_FLAGS,YourExtra=Flags"

terraform apply
```

You can also apply Terraform variables on the command line or in config files: https://www.terraform.io/docs/configuration/variables.html#assigning-values-to-root-module-variables

Note that these changes not affect an existing Terraform deployment.  They will only apply when creating the cluster.

**Comment by david-zw-liu** [comment]
Hi @displague,
Thanks for your quick reply.

Maybe I create a PR to add variable for extending feature-gates on this weekend.
